---
title: "SV_longPOG_insertion"
output: html_document
---

### Insertion Subanalysis
```{r library}
library('dplyr')
library('ggplot2')
```
```{r insertion analyses}
in_file_processed_tumour_comparison <- read.csv('../data/mock_mavis.tab', sep='\t')
in_file_processed_tumour_comparison_dup4 <- in_file_processed_tumour_comparison %>% filter(break1_chromosome != 'X') %>% filter(break1_chromosome != 'Y') 

labels_for_plot  <- c(
  'Illumina_only_HQ'="Illumina HQ",
  'Illumina_only_LQ'="Illumina LQ",
  'Nanopore_and_Illumina'="Both platforms",
  'Nanopore_only'="Nanopore only"
)

sv_platform_labeller <- function(variable,value){
  return(labels_for_plot[value])
}

ggplot(in_file_processed_tumour_comparison_dup4, aes(x =library, fill=event_type)) +
  geom_bar() +
  xlab('Sample ID') +
  ylab('Count of SV events, (n)') +
  theme(
  axis.text.x=element_blank(),
  axis.ticks.x=element_blank()) + 
  guides(fill=guide_legend(title="Event Type")) +
  facet_wrap(~Platform2, ncol = 1,strip.position = "left", scales = "free",labeller=sv_platform_labeller)


# create a dummy "translocation" entry where for every single library htere is a "SV". and its TRUE nanomonSV and TRUE SAVANA
add_missing_category <- function(df) {
  if (!any(df$Platform2 == "Nanopore_only")) {
    df <- bind_rows(df, data.frame(library = df$library[1], Platform2 = "Nanopore_only", SAVANA = TRUE, nanomonSV = TRUE))
  }
  return(df)
}

# Group by unique values in the 'library' column, apply the function, and ungroup
in_file_processed_tumour_comparison_dup5 <- in_file_processed_tumour_comparison_dup4 %>% filter((SAVANA==TRUE&nanomonSV==TRUE)|Illumina==TRUE) %>%
  group_by(library) %>%
  do(add_missing_category(.)) %>%
  ungroup()

in_file_processed_tumour_comparison_dup5$event_type[is.na(in_file_processed_tumour_comparison_dup5$event_type)] <- "No Event"
```

```{r insertion analyses signature plot }

in_file_processed_tumour_comparison_dup4 %>% group_by(library,event_type) %>% summarize(count = n()) %>% mutate(ratio = count / sum(count)* 100) %>% 
ggplot(aes(x=event_type, y=ratio)) +
    geom_boxplot()+
    geom_quasirandom(alpha=0.4) +
    labs(x = "Event Type", y = "% of calls") + theme_bw() +
  geom_text(aes(label=ifelse(event_type=='duplication'&ratio>35,as.character(library),'')),hjust=0,vjust=0)


msi_graph1 <- in_file_processed_tumour_comparison_dup4 %>% filter(Platform2 == 'Nanopore_only') %>% group_by(library,event_type) %>% summarize(count = n()) %>% mutate(ratio = count / sum(count)* 100) %>% mutate(MSI_Status = ifelse(library=='40168_N_D74665'|library=='38013_N_D36497', "MSI", 'MSS')) %>% 
ggplot(aes(x=event_type, y=ratio, color=MSI_Status)) +
    geom_boxplot(alpha=0.4, position = "dodge",outlier.shape=NA)+
    geom_quasirandom(alpha=0.7, position= "dodge", dodge.width=0.5) +
    labs(x = "Event Type", y = "Proportion of SVs, (%)") + theme_bw() +
  guides(color=guide_legend(title="MSI Status of Sample"))

insertions <- in_file_processed_tumour_comparison_dup4 %>% filter(Platform2 == 'Nanopore_only') %>% group_by(library,event_type) %>% summarize(count = n()) %>% mutate(ratio = count / sum(count)* 100) %>% mutate(MSI_Status = ifelse(library=='40168_N_D74665'|library=='38013_N_D36497', "MSI", 'MSS')) 
insertions2 <- in_file_processed_tumour_comparison_dup4 %>% filter(Platform2 == 'Nanopore_only') %>% group_by(library,event_type) %>% summarize(count = n()) %>% mutate(ratio = count / sum(count)* 100) %>% mutate(MSI_Status = ifelse(library=='40168_N_D74665'|library=='38013_N_D36497', "MSI", 'MSS')) %>% filter(event_type == 'insertion')

msi_graph2 <- in_file_processed_tumour_comparison_dup4 %>% filter(Platform2 == 'Nanopore_only') %>% group_by(library,event_type) %>% summarize(count = n()) %>% mutate(ratio = count / sum(count)* 100) %>% mutate(MSI_Status = ifelse(library=='40168_N_D74665'|library=='38013_N_D36497', "MSI", 'MSS')) %>%
ggplot(aes(x=event_type, y=count, color=MSI_Status)) +
    geom_boxplot(alpha=0.4,position = "dodge",outlier.shape=NA)+
    geom_quasirandom(alpha=0.7, position= "dodge", dodge.width=0.5) +
    labs(x = "Event Type", y = "Count of SVs, (n)") + theme_bw() +
  guides(color=guide_legend(title="MSI Status of Sample"))

prow <- plot_grid(
  msi_graph1 + xlab(''),
  msi_graph2,
  nrow = 2
)
plot_grid(prow, rel_widths = c(3, .4))

```
```{r insertions load bed regions}

repeat_masker <- read.delim('RepeatMaskerConcat.tab', col.names = c('chr','start','end','annotation')) 
gr2 <- GRanges(repeat_masker)
```

```{r insertions repeat annotations analysis}
in_file_processed_tumour_comparison_dup4$ins_size2 <- as.integer(as.character(in_file_processed_tumour_comparison_dup4$ins_size))

r1 <- in_file_processed_tumour_comparison_dup4 %>% filter(event_type == 'insertion') %>% select(break1_chromosome,break1_position_start,break2_position_end, Platform2, library, SAVANA, nanomonSV, tracking_id, ins_size2) %>% 
        rename("break1_chromosome" = "chr",
               "break1_position_start" = "start",
               "break2_position_end" = "end",
               "Platform2" = "Platform",
               "library" = "library",
               "SAVANA" = "SAVANA",
               "nanomonSV" = "nanomonSV")
r1$chr <- sub("^", "chr", r1$chr ) 
                  
table(r1$Platform)


gr1 <- GRanges(r1)

ranges <- subsetByOverlaps(gr1, gr2)

m <- findOverlaps(gr1, gr2)

gr1.matched <- gr1[queryHits(m)]

# Add the metadata from gr2
mcols(gr1.matched) <- cbind.data.frame(
    mcols(gr1.matched),
    mcols(gr2[subjectHits(m)]))


#### Whole Cohort 
insertion_repetitive_regions <- as.data.frame(gr1.matched)

# Prepare df for the future                    
r1_pog986 <- r1 %>% filter(library == '40168_N_D74665') 
table(r1_pog986$Platform)


insertion_repetitive_regions_pog986 <- insertion_repetitive_regions %>% filter(library == '40168_N_D74665') %>% distinct(library, tracking_id, .keep_all = T)
table(insertion_repetitive_regions_pog986$Platform)
```

```{r insertions repeat annotations plotting}
## Generate an upset plot of where things are falling (note - i remove low quality )

insertion_repetitive_regions <- as.data.frame(gr1.matched)
insertion_repetitive_regions$SINE <- grepl("SINE", insertion_repetitive_regions$annotation)
insertion_repetitive_regions$LINE <- grepl("LINE", insertion_repetitive_regions$annotation)
insertion_repetitive_regions$simple_repeat <- grepl("repeat", insertion_repetitive_regions$annotation)
insertion_repetitive_regions$centromere <- grepl("ct", insertion_repetitive_regions$annotation)

insertion_repetitive_regions$other <- ifelse(insertion_repetitive_regions$SINE ==FALSE& 
                                             insertion_repetitive_regions$LINE ==FALSE& 
                                              insertion_repetitive_regions$simple_repeat ==FALSE& 
                                              insertion_repetitive_regions$centromere ==FALSE, 
                                              TRUE, FALSE
                                              )
  

list_of_cols = c('SINE', 'LINE', 'simple_repeat', 'other')

# Only POG986 and two Nanopore calls
ComplexUpset::upset(
  insertion_repetitive_regions %>% filter((library == '40168_N_D74665') & Platform == 'Nanopore_only'),
  list_of_cols,
  annotations = list(
      'SV Length'=(
      ggplot(mapping=aes(y=ins_size2))
      + geom_quasirandom(na.rm=TRUE)
      )
  )
)


```

```{r insertions continual analysis - non-overlapping regions }
# A lot of POG986 calls are not mapping to repetitive regions. where are they going then? 

r1_pog986_not_overlapping <- subset(r1_pog986, !(tracking_id %in% insertion_repetitive_regions_pog986$tracking_id))
high_quality_ins <- r1_pog986_not_overlapping %>% filter(nanomonSV==TRUE &SAVANA==TRUE&ins_size2>50) 
r1_pog986_not_overlapping %>% filter(nanomonSV==TRUE &SAVANA==TRUE&ins_size2>50) %>% ggplot(aes(x=chr, fill=Platform)) + geom_bar() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```
